apiVersion: batch/v1
kind: Job
metadata:
  name: ti-migration-release-77
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "ti-service.labels" . | nindent 4 }}
    # "helm.sh/hook": post-install,post-upgrade
    # "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  #ttlSecondsAfterFinished: 100
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ti-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: migrate
        image: {{ .Values.jobs.migrate.image.repository}}:{{ .Values.jobs.migrate.image.tag}}
        imagePullPolicy: {{ .Values.jobs.migrate.image.pullPolicy}}
        command: ["/bin/bash", "-c", "/opt/harness/migrate.sh" ]
        resources:
          {{- toYaml .Values.jobresources | nindent 10 }}
        env:
          - name: MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: harness-secret
                key: mongodbUsername
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: harness-secret
                key: mongodbPassword
          - name: TI_SERVICE_MONGODB_CONN_STR
            value: 'mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@mongodb-replicaset-chart-0.mongodb-replicaset-chart.{{ .Release.Namespace }}.svc:27017/ti-harness?authSource=admin'
          - name: TI_SERVICE_TIMESCALE_USERNAME
            value: "postgres"
          - name: TI_SERVICE_TIMESCALE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: harness-secret
                key: "timescaledbPostgressPassword"
          - name: TSDB_URL
            value: 'postgres://postgres:$(TI_SERVICE_TIMESCALE_PASSWORD)@timescaledb-single-chart.{{ .Release.Namespace }}:5432/harnessti'
      restartPolicy: Never
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
      {{- end }}

