apiVersion: v1
kind: Service
metadata:
  name: ti-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ti-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: ti-service
    port: {{.Values.service.port}}
    protocol: TCP
    targetPort: {{.Values.service.port}}
  selector:
    {{- include "ti-service.selectorLabels" . | nindent 4 }}
