apiVersion: v1
entries:
  ti-service:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-08-19T06:59:06.331626-04:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.16.1
    - name: harness-common
      repository: https://harness.github.io/helm-common/charts
      version: 0.1.1
    description: A Helm chart for Kubernetes
    digest: 438dacb21e985eb873d9d2a4e6ed8dd0ad3831b96c6d2c0828bf3d346791d2da
    name: ti-service
    type: application
    urls:
    - ti-service-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-08-19T06:59:06.330061-04:00"
    dependencies:
    - name: harness-common
      repository: https://harness.github.io/helm-common/charts
      version: 0.1.1
    description: A Helm chart for Kubernetes
    digest: d16f24a1e012a67be06550db73505efd81c4ebc36074d6f8dc163c87487a2239
    name: ti-service
    type: application
    urls:
    - ti-service-0.1.0.tgz
    version: 0.1.0
generated: "2022-08-19T06:59:06.328772-04:00"
